# SPDX-FileCopyrightText: 2022 Google LLC
# SPDX-FileCopyrightText: 2026 Florian Wilhelm <fwilhelm.wgt+github@gmail.com>
#
# Notice: This file was modified by Florian Wilhelm on 2026-08-22
# to build and package the grind cli.
#
# https://github.com/GoogleContainerTools/distroless/blob/cd080764af3103b2f49fb5eb23297c72c945e77a/examples/rust/Dockerfile
#
# SPDX-License-Identifier: Apache-2.0

FROM rust:1 as build-env
WORKDIR /app
COPY . /app
RUN cargo build --release -p grind-cli

FROM gcr.io/distroless/cc-debian12
COPY --from=build-env /app/target/release/grind /
CMD ["./grind"]