#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Florian Wilhelm <fwilhelm.wgt+github@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# How big is grind, and where did it grow? Count one commit's lines, add them to
# `history.json`, and rebuild `loc.fods` from `loc.rhai` — a spreadsheet that lives in git
# and is regenerated by a script, which is the point of keeping it here (doc/dsl.md layer 1).
#
#   examples/loc/update.sh                 # count HEAD
#   examples/loc/update.sh v0.3.0 abc1234  # count these, in any order
#   examples/loc/update.sh --rebuild       # count nothing, just rebuild loc.fods
#   GRIND=target/debug/grind examples/loc/update.sh   # a binary other than the one on PATH
#
# Meant to run once per release, after the tag exists, so the snapshot carries its name.
# Counting re-runs replace the commit's own entry rather than adding a second one, and each
# commit is read straight out of git (`git grep REV`), so nothing is checked out and the
# working tree may be dirty. The history is data and the spreadsheet is a build product:
# the one is edited by this script, the other is never edited at all.
#
# What a line is, so the numbers mean the same thing every release:
#
#   * a non-blank line of a `.rs` file — comments count, because in this codebase the
#     comment is half the work;
#   * filed under the top-level directory it lives in, which is the crate (`sheet/`,
#     `ui_tui/`, …) — a crate that was renamed shows up under both names, which is history
#     rather than a bug;
#   * `tests` is the share of those lines under a `tests/` directory;
#   * a file whose first line says it is generated (`// Generated by`, `@generated`) is not
#     counted at all — `core/src/third_party/data.rs` is fifteen thousand lines of licence
#     table nobody wrote;
#   * `docs` is the non-blank lines of `doc/*.md`, the specs and plans beside the code.
#
# Needs `git` and `jq`.

set -euo pipefail

GRIND=${GRIND:-grind}
here=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
history="$here/history.json"
cd "$(git -C "$here" rev-parse --show-toplevel)"

[[ -f $history ]] || echo '{"snapshots": []}' >"$history"

# One snapshot of one commit, as a JSON object on stdout.
count() {
    local rev=$1 commit date time tag
    commit=$(git rev-parse --short=7 "$rev^{commit}")
    date=$(git log -1 --format=%cs "$commit")
    time=$(git log -1 --format=%cI "$commit")
    tag=$(git tag --points-at "$commit" | sort -V | tail -1)

    # `REV:path:N` for every file whose first line declares it generated.
    local generated
    generated=$(git grep -n -E '^(// Generated by|// @generated)' "$commit" -- '*.rs' |
        awk -F: '$3 == 1 { print $2 }')

    # `REV:path:count`, non-blank lines only. Files with no such line are not listed at all,
    # which is the right answer for them.
    git grep -c -E '[^[:space:]]' "$commit" -- '*.rs' |
        awk -F: -v skip="$generated" -v commit="$commit" -v date="$date" -v time="$time" -v tag="$tag" '
            BEGIN { n = split(skip, s, "\n"); for (i = 1; i <= n; i++) generated[s[i]] = 1 }
            {
                path = $2; lines = $3
                if (path in generated) next
                crate = (index(path, "/") ? substr(path, 1, index(path, "/") - 1) : "(root)")
                crates[crate] += lines
                if (path ~ /(^|\/)tests\//) tests += lines
                files++
            }
            END {
                printf "{\"commit\":\"%s\",\"date\":\"%s\",\"time\":\"%s\",\"tag\":\"%s\",\"files\":%d,\"tests\":%d,\"crates\":{", commit, date, time, tag, files, tests
                sep = ""
                for (c in crates) { printf "%s\"%s\":%d", sep, c, crates[c]; sep = "," }
                printf "}}\n"
            }' |
        jq --argjson docs "$(git grep -c -E '[^[:space:]]' "$commit" -- 'doc/*.md' |
            awk -F: '{ n += $3 } END { print n + 0 }')" '. + {docs: $docs}'
}

rebuild=false
revs=()
for arg in "$@"; do
    case $arg in
    --rebuild) rebuild=true ;;
    *) revs+=("$arg") ;;
    esac
done
[[ $rebuild == true || ${#revs[@]} -gt 0 ]] || revs=(HEAD)

for rev in "${revs[@]}"; do
    snapshot=$(count "$rev")
    echo "counted $(jq -r '"\(.commit) (\(.date)): \([.crates[]] | add) lines of Rust"' <<<"$snapshot")"
    # Replace this commit's own entry if it has one, then keep the history in time order —
    # the spreadsheet's rows are in the order the array is in.
    jq --argjson s "$snapshot" '
        .snapshots = ([.snapshots[] | select(.commit != $s.commit)] + [$s]
                      | sort_by(.time)
                      | map(.crates |= (to_entries | sort_by(.key) | from_entries)))
    ' "$history" >"$history.new"
    mv "$history.new" "$history"
done

"$GRIND" build "$here/loc.rhai" -o "$here/loc.fods"
echo "wrote $here/loc.fods"
